preload = ~/Pictures/2019_green_lamborghini_huracan_evo_spyder_supercar-wallpaper-5120x1440.jpg

wallpaper = DP-1,~/Pictures/horizon_zero_dawn_2017_video_game-wallpaper-5120x1440.jpg
wallpaper = DP-5,~/Pictures/dune_awakening_2023_video_game-wallpaper-5120x1440.jpg
wallpaper = DP-5,~/Pictures/2019_green_lamborghini_huracan_evo_spyder_supercar-wallpaper-5120x1440.jpg

splash = true
