#  _   _                  _                 _  
# | | | |_   _ _ __  _ __| | __ _ _ __   __| | 
# | |_| | | | | '_ \| '__| |/ _` | '_ \ / _` | 
# |  _  | |_| | |_) | |  | | (_| | | | | (_| | 
# |_| |_|\__, | .__/|_|  |_|\__,_|_| |_|\__,_| 
#        |___/|_|                              
#  
# ----------------------------------------------------- 

$browser = "vivaldi"
$shell = "kitty"

$script_dir = ~/.config/hypr/scripts
$theme_dir = ~/.config/hypr/theme
$conf_dir = ~/.config/hypr/conf

$mainMod = SUPER

source = $theme_dir/mocha.conf

source = $conf_dir/monitor.conf
source = $conf_dir/autostart.conf
source = $conf_dir/environment.conf
source = $conf_dir/input.conf
source = $conf_dir/window.conf
source = $conf_dir/decorations.conf
source = $conf_dir/layouts.conf
source = $conf_dir/misc.conf
source = $conf_dir/keybindings.conf
source = $conf_dir/windowrules.conf
source = $conf_dir/animations.conf

binds {
    workspace_back_and_forth = true
}


exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
