#!/bin/zsh
##? ya - Yazi file manager shell wrapper that provides the ability to change the current working directory when exiting.

local tmp="$(mktemp -t "yazi-cwd.XXXXX")"
yazi "$@" --cwd-file="$tmp"
if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
    cd -- "$cwd"
fi
rm -f -- "$tmp"

