#!/bin/env bash

current_layout=$(hyprctl -j getoption general:layout | jq '.str' | sed 's/"//g')

case ${current_layout} in
"master")
	hyprctl keyword general:layout dwindle
	notify-send -i "$HOME/.config/hypr/icons/hyprland.png" "Layout" "Dwindle"
	;;
"dwindle")
	hyprctl keyword general:layout master
	notify-send -i "$HOME/.config/hypr/icons/hyprland.png" "Layout" "Master"
	;;
*) ;;
esac
