# Start Polkit
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# Notification manager
exec-once = mako

# Clipboard text & images
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Restart pipewire
exec-once = systemctl --user restart pipewire

# Wallpaper
# exec-once = hyprpaper

# Waybar
exec-once = waybar

# Using hypridle to start hyprlock
exec-once = hypridle

# Autostart some frequently used apps
exec-once = [workspace 1 silent] $browser
exec-once = [workspace 2 silent] $shell
