# Start Polkit
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# Notification manager
exec-once = /usr/bin/mako

# Clipboard text & images
exec-once = /usr/bin/wl-paste --type text --watch cliphist store
exec-once = /usr/bin/wl-paste --type image --watch cliphist store

# Restart pipewire
exec-once = /usr/bin/systemctl --user restart pipewire

# Wallpaper
# exec-once = hyprpaper

# Start tray apps
exec-once = /usr/bin/nm-applet
exec-once = /usr/bin/blueman-applet
exec-once = /usr/bin/bitwarden-desktop

# Waybar
exec-once = /usr/bin/waybar

# Using hypridle to start hyprlock
exec-once = /usr/bin/hypridle

# Autostart some frequently used apps
exec-once = [workspace 1 silent] $browser
exec-once = [workspace 2 silent] $shell

