# Portal
exec-once = ~/.config/hypr/scripts/reset-xdg-portal

# Start Polkit
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# Notification manager
# exec-once = /usr/bin/mako

# Clipboard text & images
exec-once = /usr/bin/wl-paste --type text --watch cliphist store
exec-once = /usr/bin/wl-paste --type image --watch cliphist store

# Restart pipewire
exec-once = /usr/bin/systemctl --user restart pipewire

# Wallpaper
exec-once = /usr/bin/hyprpaper

# Start tray apps
exec-once = /usr/bin/nm-applet
exec-once = /usr/bin/blueman-applet
exec-once = /usr/bin/bitwarden-desktop

# Waybar
# exec-once = /usr/bin/waybar

# Hyprpanel
exec-once = /usr/bin/hyprpanel

# Using hypridle to start hyprlock
exec-once = /usr/bin/hypridle

# Autostart some frequently used apps
exec-once = [workspace 1 silent] $shell
exec-once = [workspace 1 silent] $browser

# specific settings to enable dark mode GTK apps
exec = gsettings set org.gnome.desktop.interface gtk-theme "Juno-palenight-v40"   # for GTK3 apps
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps
