# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
input {
    kb_layout = us,us
    kb_variant = ,colemak_dh
    kb_model =
    kb_options =
    kb_rules =

    repeat_delay = 250
    repeat_rate = 60

    follow_mouse = 1

    touchpad {
        natural_scroll = yes
    }

    sensitivity = -0.1
    accel_profile = "flat"
}

# connected to Bluetooth
device:"keychron-k5-pro"-keyboard {
    kb_layout = us,us
    kb_variant = ,colemak_dh
}

# connected to USB-C
device:keychron-keychron-k5-pro {
    kb_layout = us,us
    kb_variant = ,colemak_dh
}
