misc {
    disable_hyprland_logo = false
    disable_splash_rendering = true

    mouse_move_enables_dpms = true
    hide_cursor_on_key_press = true

    vfr = true
    vrr = 2

    enable_swallow = true
    swallow_regex = ^(Alacritty|kitty|footclient)$
}
