general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    gaps_in = 4
    gaps_out = 4
    border_size = 2

    col.active_border = rgba(bb9af7ff) rgba(7dcfffee) 45deg
    col.inactive_border = rgba(414868ee)

    layout = dwindle
}

