# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# Per window rules
windowrule = float, file_progress
windowrule = float, confirm
windowrule = float, dialog
windowrule = float, download
windowrule = float, notification
windowrule = float, error
windowrule = float, splash
windowrule = float, confirmreset
windowrule = float, title:Open File
windowrule = float, title:branchdialog
windowrule = float, Lxappearance
windowrule = float, qalculate-qt
windowrule = size 600x400, qalculate-qt
windowrule = center, qalculate-qt
windowrule = float, Rofi
windowrule = float, file-roller
windowrule = fullscreen, wlogout
windowrule = float, title:wlogout
windowrule = fullscreen, title:wlogout
windowrulev2 = center,class:^(pavucontrol)$
windowrulev2 = move 5% 10%,class:^(pavucontrol)$
windowrulev2 = float,class:^(pavucontrol)$
windowrulev2 = size 800 600,class:^(pavucontrol)$
windowrule = opacity 0.92, Thunar
windowrule = float, nm-connection-editor
windowrule = center, nm-connection-editor
windowrule = float, org.kde.polkit-kde-authentication-agent-1
windowrule = center, org.kde.polkit-kde-authentication-agent-1
windowrulev2 = fullscreen, class:^(looking-glass-client)$
windowrulev2 = float, class:^(com.cisco.anyconnect.gui)$
windowrulev2 = workspace 9, class:^(com.cisco.anyconnect.gui)$
windowrulev2 = noinitialfocus, class:^(com.cisco.anyconnect.gui)$
windowrulev2 = move 100%-w-20 5%, class:^(com.cisco.anyconnect.gui)$

# Layer rules
layerrule = blur, gtk-layer-shell

# Rules for Vivaldi update where popup menus are now windows :-S
# Yes, they indeed have no title, class (or initialTitle, initialClass)
windowrulev2 = rounding 0,class:^$
windowrulev2 = bordersize 0,class:^$
windowrulev2 = noblur,class:^$
windowrulev2 = noshadow,class:^$
windowrulev2 = opaque,class:^$
