# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# Per window rules
windowrule = float, file_progress
windowrule = float, confirm
windowrule = float, dialog
windowrule = float, download
windowrule = float, notification
windowrule = float, error
windowrule = float, splash
windowrule = float, confirmreset
windowrule = float, title:Open File
windowrule = float, title:branchdialog
windowrule = float, Lxappearance
windowrule = float, qalculate-qt
windowrule = size 600x400, qalculate-qt
windowrule = center, qalculate-qt
windowrule = float, Rofi
windowrule = float, file-roller
windowrule = fullscreen, wlogout
windowrule = float, title:wlogout
windowrule = fullscreen, title:wlogout
windowrule = size 800 600,title:^(Volume Control)$
windowrule = float,title:^(Volume Control)$
# windowrule = opacity 0.42,title:^(Volume Control)$
windowrule = opacity 0.92, Thunar
windowrule = float, nm-connection-editor
windowrule = center, nm-connection-editor
windowrule = float, org.kde.polkit-kde-authentication-agent-1
windowrule = center, org.kde.polkit-kde-authentication-agent-1
windowrulev2 = fullscreen, class:^(looking-glass-client)$

# Layer rules
layerrule = blur, gtk-layer-shell

