general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    gaps_in = 4
    gaps_out = 4
    border_size = 2

    col.active_border = 0xa0$mauveAlpha 0xd0$lavenderAlpha 45deg
    col.inactive_border = $overlay0

    layout = dwindle
}

